// react-js/06-Redux/01-Basic-GET-using-Fetch/src/components/EmployeeList.jsx
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import * as employeeActions from '../actions/employeeActions';

class EmployeeList extends Component {
    constructor(...args) {
        super(...args);
    }

    render() {

        let renderEmpRowsList = () => {
            let empRowsList = [];
            for (let i = 0; i < this.props.employees.length; i++) {
                let r = this.props.employees[i];
                empRowsList.push(
                    <tr key={r.Empno}>
                        <th scope="row">
                            {r.Empno}
                        </th>
                        <td>{r.Ename}</td>
                        <td>{r.Sal}</td>
                    </tr>
                );
            }
            return empRowsList;
        };

        return (
            <div className="container">
                <div className="row">
                    <div className="col-auto mr-auto">
                        <h3>List of Employees</h3>
                    </div>
                </div>
                <div>
                    <table className="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Salary</th>
                            </tr>
                        </thead>
                        <tbody>
                            {renderEmpRowsList()}
                        </tbody>
                    </table>
                </div >
            </div >
        )
    }
}

function mapStateToProps(state, ownProps) {
    return {
        employees: state.employees
    };
}

function mapDispatchToProps(dispatch) {
    return {
        actions: bindActionCreators(employeeActions, dispatch)
    };
}

export default connect(mapStateToProps, mapDispatchToProps)(EmployeeList);

// vue-js/05-vuex/04-router, vuex, ajax, master, detail/src/components/EmployeeList.vue
<template>
    <div class="container">
      <div class="row">
        <div class="col-auto mr-auto">
          <h3>List of Employees</h3>
        </div>
        <div class="col-auto">
          <button @click="refresh" class="btn btn-primary">Refresh</button>
        </div>
      </div>
      <div v-if="PENDING" class="alert alert-info" role="alert">Loading..</div>
      <div v-if="!PENDING && !FAILURE">
        <table class="table">
          <thead >
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Salary</th>
          </thead>
          <tbody>
            <tr v-for="(item) in data" :key="item.Empno">
              <th scope="row">
                <router-link :to="{name: 'EmpDetail', params: {empno:item.Empno}}">{{item.Empno}}</router-link>                
              </th>
              <td>{{item.Ename}}</td>
              <td>{{item.Sal}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>    
</template>
<script>
import { mapGetters } from "vuex";
import api from "./../store/api";

export default {
  name: "EmployeeList",
  data() {
    return {
      data: null
    };
  },
  created() {
    this.refresh();
  },
  computed: {
    ...mapGetters(["PENDING", "FAILURE", "DATA_ERROR"])
  },
  methods: {
    refresh() {
      api.getEmployeesAsync().then(data => {
        this.data = data;
      });
    }
  }
};
</script>
